# Generated by Django 2.1.2 on 2019-05-11 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0007_auto_20190511_1516'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_waste', models.FloatField(default=-1.0)),
                ('monthly_waste', models.FloatField(default=-1.0)),
                ('monthly_budget', models.FloatField(default=-1.0)),
                ('current_day', models.IntegerField(default=-1)),
                ('current_month', models.IntegerField(default=-1)),
                ('energy_plan', models.FloatField(default=-1.0)),
                ('days', models.ManyToManyField(blank=True, to='nodes.Day')),
                ('divisions', models.ManyToManyField(blank=True, to='nodes.Division')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
