# Generated by Django 2.1.2 on 2019-05-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodemcu',
            name='current_waste',
            field=models.IntegerField(default=-1),
        ),
    ]
