# Generated by Django 2.1.2 on 2019-05-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_auto_20190508_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodemcu',
            name='curr_day',
            field=models.IntegerField(default=-1),
        ),
    ]
