# Generated by Django 2.1.2 on 2019-05-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0005_nodemcu_curr_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodemcu',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
