# Generated by Django 2.1.2 on 2019-05-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0006_nodemcu_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(default=-1)),
                ('energy_per_day', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.CreateModel(
            name='DivionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('monthly_waste', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('daily_waste', models.FloatField(default=-1.0)),
                ('monthly_waste', models.FloatField(default=-1.0)),
                ('days', models.ManyToManyField(blank=True, to='nodes.Day')),
            ],
        ),
        migrations.CreateModel(
            name='Plug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=100)),
                ('current_monthly_waste', models.FloatField(default=-1.0)),
                ('current_daily_waste', models.FloatField(default=-1.0)),
                ('on', models.BooleanField(default=True)),
                ('current_day', models.IntegerField(default=-1)),
            ],
        ),
        migrations.DeleteModel(
            name='NodeMCU',
        ),
        migrations.AddField(
            model_name='division',
            name='products',
            field=models.ManyToManyField(blank=True, to='nodes.Plug'),
        ),
        migrations.AddField(
            model_name='division',
            name='users',
            field=models.ManyToManyField(blank=True, to='nodes.DivionUser'),
        ),
    ]
