# Generated by Django 2.1.2 on 2019-05-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0007_auto_20190511_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='plug',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
