# Generated by Django 2.1.2 on 2019-05-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0008_plug_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plug',
            name='days',
            field=models.ManyToManyField(blank=True, to='nodes.Day'),
        ),
    ]
