# Generated by Django 2.1.2 on 2019-05-11 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0009_plug_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='users',
        ),
        migrations.DeleteModel(
            name='DivionUser',
        ),
    ]
