# Generated by Django 2.1.2 on 2019-05-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0010_auto_20190511_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=-1.0)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
